### PR TITLE
Update links and link to travis status page of duartemolha

### PR DESCRIPTION
**Pull request by mmterpstra**
This PR (pull request) is based on your comments at https://github.com/molgenis/CoNVaDING/pull/41. Also I work at the same institution as the original authors but the one who was working on the program is leaving and before he left they were considering to update the code. 
This was canceled due to the sheer amount of changed code to the project.

Changes
   - Update readme on how to commit
   - Update links to point at the correct repo's
   - Errors on empty bed file (which might happen due to streaming).
   - updated the travis buid status to `image` or image so now @duartemolha you have to enable building it with travis at https://travis-ci.org/account/repositories

### CODE REVIEW

**Comment by duartemolha** [comment]
thanks... it would make sense maybe incorporate all these changes in a new branch of the main repo and continue to develop it there instead of my fork?

**Comment by mmterpstra** [comment]
That's not my question to answer so @ljohansson @freerkvandijk pls respond.

**Comment by duartemolha** [comment]
It is not successfully built... thanks @mmterpstra

**Comment by mmterpstra** [comment]
now it is! see: https://travis-ci.org/duartemolha/CoNVaDING_reload

exit code 0 is good and any other value is wrong, see also http://www.tldp.org/LDP/abs/html/exitcodes.html .

**Comment by duartemolha** [comment]
yes... I know... it was a typo... I meant " It is now successfully built...
thanks" :)

**Pull request merged**
